fix: instrument macro expects a string literal
a variable is being passed to instrument macro, raising this error:

error: expected string literal
    |
161 |     #[instrument(level = "trace", target = TARGET, skip_all)]

this commit fixes it